on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}        
        
      - name: Deploy dev
        uses: docker pull dtzar/helm-kubectl
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        with:
          script: |
            helm repo add zebrands https://ramiroduarteavalos.github.io/library/charts
            apk add git
            git clone https://github.com/ramiroduarteavalos/devops
            helm upgrade ${{ github.repository }} --install zebrands/zebrands -n dev -f devops/values.yaml -f devops/values.dev.yaml -f devops/${{ github.repository }}/vales.yaml -f devops/${{ github.repository }}/values.dev.yaml       
            
      - name: Deploy prod
        uses: docker pull dtzar/helm-kubectl
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          script: |
            helm repo add zebrands https://ramiroduarteavalos.github.io/library/charts
            apk add git
            git clone https://github.com/ramiroduarteavalos/devops
            helm upgrade ${{ github.repository }} --install zebrands/zebrands -n dev -f devops/values.yaml -f devops/values.prod.yaml -f devops/${{ github.repository }}/vales.yaml -f devops/${{ github.repository }}/values.prod.yaml                   
